### ISSUE TITLE
Can't Sign In User

### ISSUE THREAD

**Issue by TimmyRB** [ottomated/flutter_snapchat#3]
When I run
```
Future<void> snapLogin() async {
    var snapchat = SnapchatPlugin();
    await snapchat.init();

    SnapchatUser user = await snapchat.login();
    print("Logged in: " + user.displayName);
  }
```
I get this as an error then the app crashes
```
E/AndroidRuntime(  834): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime(  834): Process: com.company.app, PID: 834
E/AndroidRuntime(  834): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime(  834): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
E/AndroidRuntime(  834): 	at com.google.gson.Gson.fromJson(Gson.java:927)
E/AndroidRuntime(  834): 	at com.google.gson.Gson.fromJson(Gson.java:865)
E/AndroidRuntime(  834): 	at com.snapchat.kit.sdk.core.networking.e.intercept(SourceFile:85)
E/AndroidRuntime(  834): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(  834): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AndroidRuntime(  834): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
E/AndroidRuntime(  834): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
E/AndroidRuntime(  834): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime(  834): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(  834): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(  834): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(  834): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime(  834): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
E/AndroidRuntime(  834): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
E/AndroidRuntime(  834): 	... 11 more
E/AndroidRuntime(  834): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime(  834): Process: com.company.app, PID: 834
E/AndroidRuntime(  834): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime(  834): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
E/AndroidRuntime(  834): 	at com.google.gson.Gson.fromJson(Gson.java:927)
E/AndroidRuntime(  834): 	at com.google.gson.Gson.fromJson(Gson.java:865)
E/AndroidRuntime(  834): 	at com.snapchat.kit.sdk.core.networking.e.intercept(SourceFile:85)
E/AndroidRuntime(  834): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(  834): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AndroidRuntime(  834): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
E/AndroidRuntime(  834): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
E/AndroidRuntime(  834): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime(  834): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(  834): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(  834): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(  834): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime(  834): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
E/AndroidRuntime(  834): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
E/AndroidRuntime(  834): 	... 11 more
I/Process (  834): Sending signal. PID: 834 SIG: 9
```

**Comment by TimmyRB** [comment]
Figured it out, you have to use your
`CLIENT ID FOR NON-CONFIDENTIAL OAUTH2 FLOW`
token instead of your
`CLIENT ID FOR CONFIDENTIAL OAUTH2 FLOW`
token

**Comment by amanzimble** [comment]
Hi, My app not Redirect in app after successfully Login? 
Is there any callback problem. My app is Live and Activated on Snapchat Portal
